#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ReceiptPrinter.Resource", IsApplication=true)]

namespace ReceiptPrinter
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MainLayout = 2131034112;
			
			// aapt resource value: 0x7f050019
			public const int buttonReset = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int buttonSend = 2131034136;
			
			// aapt resource value: 0x7f05000f
			public const int checkBoxText = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int checkBoxTextBold = 2131034130;
			
			// aapt resource value: 0x7f050007
			public const int checkBoxTitle = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int checkBoxTitleBold = 2131034122;
			
			// aapt resource value: 0x7f050010
			public const int editTextText = 2131034128;
			
			// aapt resource value: 0x7f050008
			public const int editTextTitle = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout1 = 2131034113;
			
			// aapt resource value: 0x7f050017
			public const int linearLayoutButton = 2131034135;
			
			// aapt resource value: 0x7f050011
			public const int linearLayoutText = 2131034129;
			
			// aapt resource value: 0x7f050009
			public const int linearLayoutTitle = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int radioButtonNow = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int radioButtonReserve = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int radioGroup1 = 2131034114;
			
			// aapt resource value: 0x7f050014
			public const int spinnerTextAlign = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int spinnerTextSize = 2131034134;
			
			// aapt resource value: 0x7f05000c
			public const int spinnerTitleAlign = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int spinnerTitleSize = 2131034126;
			
			// aapt resource value: 0x7f050005
			public const int textViewDate = 2131034117;
			
			// aapt resource value: 0x7f050013
			public const int textViewTextAlign = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int textViewTextSize = 2131034133;
			
			// aapt resource value: 0x7f050006
			public const int textViewTime = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int textViewTitleAlign = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int textViewTitleSize = 2131034125;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
